# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBranches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('parent_company', models.CharField(max_length=200)),
                ('street_number', models.IntegerField()),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('telephone', models.IntegerField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('collect', models.BooleanField()),
                ('deliver', models.BooleanField()),
                ('date_created', models.DateField(auto_now=True)),
                ('logo', models.FileField(default='images/products/logo.jpg', upload_to='images/logos/')),
                ('created_by', models.CharField(default='admin', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShopHeadquaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_headquaters_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=200)),
                ('street_number', models.IntegerField()),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('telephone', models.IntegerField()),
                ('website', models.URLField()),
                ('date_created', models.DateField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.FileField(default='images/products/image_1.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.FileField(default='images/products/image_2.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.FileField(default='images/products/image_3.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.FileField(default='images/products/image_4.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.FileField(default='images/products/image_5.jpg', upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='shopcatalogue',
            name='created_by',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='shopcatalogue',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_units',
            field=models.CharField(max_length=200),
        ),
    ]
