# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170708_0609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopBranches',
            new_name='ShopBranch',
        ),
    ]
