# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170708_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='shopbranch',
            options={'verbose_name_plural': 'shop Branches'},
        ),
        migrations.AlterModelOptions(
            name='shopcatalogue',
            options={'verbose_name_plural': 'shop Catalogues'},
        ),
        migrations.AlterModelOptions(
            name='shopheadquaters',
            options={'verbose_name_plural': 'shop Headquaters'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Category', to_field='name'),
        ),
    ]
